### ISSUE TITLE
Cannot index bgzipped FASTA file with Bio::DB:Fasta

### ISSUE THREAD

**Issue by HagenC** [kircherlab/CADD-scripts#10]
Hi, 

I get this error below - how can I resolve this?

![image](https://user-images.githubusercontent.com/16817639/64234591-f4738980-cef6-11e9-9862-143fe5c9a25f.png)

Cheers

**Comment by aerval** [comment]
Sorry, I cannot reproduce this with the information given. Did CADD work for you previously (I assume this since you had raised another issue before)? This error messages seems to regard to the reference genome file that is stored under `data/annotations/GRCh37_v1.4/reference/` that may be missing its index file `reference.fa.fai` though that should have been provided (and should also not be an issue to generate).

**Comment by HagenC** [comment]
Good morning,

Thanks for the reply.

Yes, that is correct -  I use CADD on a different cluster partion. I got it to work back then relying on shared modules (anaconda 2.2.0, ensemble-vep 91 etc) and hash-out the "`source activate cadd-env`" in `CADD.sh.` The cluster I am trying to install CADD on now, jave outdated modules so I have to rely on `cadd-env` and I can´t install Miniconda2.

Anyway, I got it to work by loading Anaconda 5.2.0  :)

Concerning the `data/annotations/GRCh37_v1.4/reference/` both `.fa` and .`fa.fai` are present- so they are provided and that was not the issue. I have actually no clue what the issue was, but it works now :)

Thanks for the help.
