### ISSUE TITLE
Snakemake Multi-core support

### ISSUE THREAD

**Issue by williamphu** [kircherlab/CADD-scripts#24]
Hi all,

I'm having trouble getting CADD to run on multiple cores. In the help description, there's an option for multiple cores, but in `CADD.sh` the option for multiple cores on line 38 was originally `v) CORES=$OPTARG`, which I modified to `c) CORES=$OPTARG`, in line with the documentation. This allows the program to report that Snakemake is using up multiple cores, but checked CPU usage does not reflect that. Are there only certain parts of the code that have multi-core support?

Thanks.

**Comment by makirc** [comment]
Hi William, 
I am not aware of any of the scripts making actual use of multiple cores. I also don't think that Ensembl VEP makes use of it (at least I did not see anything in its documentation on a brief look). We usually parallelize by splitting up variant lists and running separate CADD instances. 
Best,
Martin

**Comment by williamphu** [comment]
Great, thanks you!

**Comment by aerval** [comment]
The reason we included the parameter was because the first versions of CADD v1.6 generated the annotations for MMSplice themselves (optionally via multicore) which is replaced now by a precomputed annotation. Further, snakemake nowadays requires setting the `--cores` (or jobs) argument.

Thanks for letting us know of the issue.
