### ISSUE TITLE
Release a 1.6.1 version of scripts?

### ISSUE THREAD

**Issue by holtgrewe** [kircherlab/CADD-scripts#29]
It would be nice to have the latest changes of the install.sh in a release so the downstream conda package can benefit from this.

**Comment by visze** [comment]
it is also possible to name them `1.6-1` to make it different from CADD 1.6

**Comment by visze** [comment]
or `1.6s1` or with any other letter

**Comment by aerval** [comment]
The problem here is that 1.6 is the score release, not the software release. As Max is proposing, I would prefere a clear separation between CADD score version number and scripts number, i.e CADD-scripts 1.6 release 1 to in principle account for a CADD version 1.6.1 that will be matched by CADD-scripts 1.6.1 release 1
