### ISSUE TITLE
CADD script fails on empty input

### ISSUE THREAD

**Issue by holtgrewe** [kircherlab/CADD-scripts#30]
It would be nice if this was handled a bit more gracefully than a Snakemake crash.

**Comment by aerval** [comment]
I am not sure if this fixes the problem you have.

The way the title describes the problem, CADD should fail the following code:
```
touch empty.vcf
./CADD.sh empty.vcf
```
which does not happen. Neither is an error observed if the file input file is not empty but only contains a

The associated bugfix fixes what happens when no input file is specified at all or if the specified input file does not exist. However, none of this is associated with any 'Snakemake crash', so please describe the problem in detail.
