### ISSUE TITLE
Getting both imputation file along with annotation file 

### ISSUE THREAD

**Issue by SBNoor** [kircherlab/CADD-scripts#34]
I am running CADD script on my system to get annotations for my vcf file. However, CADD.sh seems to remove the imputation file at the end. I want to retain the imputation file too. How can I do that? I made changes to snakeMake file whereby I remove the last two rules and in CADD.sh as I give $Name.csv.gz as TMP_OUTFILE. But this produces an empty imputation file. Is there another way to obtain imputation file?

**Comment by aerval** [comment]
Hello,

In order to do that, you have to make the imputation file none temporary and at the end move it to a none temporary location.
This means
1. changing line 69 in Snakefile to 
```
    output: '{file}.csv.gz'
```
and in CADD.sh:
2. adding the imputation file as a named file, i.e inserting past line 119:
```
TMP_IMPFILE=$TMP_FOLDER/$NAME.csv.gz
```
3. moving said file to a save location `SOME_FILEPATH`, i.e inserting around line 129
```
mv $TMP_IMPFILE $SOME_FILEPATH
```

I hope that helps,

Philipp

**Comment by SBNoor** [comment]
Yes this worked. Thank you!
