### ISSUE TITLE
Dependancy Error on CADD installation

### ISSUE THREAD

**Issue by sreeshmaraj** [kircherlab/CADD-scripts#47]
I am trying to install the CADD tool v1.6. i downloaded the Zip file from GitHub and installed snakemake, when i runned the install.sh in a new conda environment and am getting some conflict error.
I am attaching the error file here.
[v.16_error.txt](https://github.com/kircherlab/CADD-scripts/files/13715220/v.16_error.txt)

I also tried to install version 1.5 and am getting some conflict error and also attaching the error message here.

[v1.5_error.txt](https://github.com/kircherlab/CADD-scripts/files/13715308/v1.5_error.txt)

I wanted to execute CADD  and any help will be appreciable.

Thank you in advance.

**Comment by aerval** [comment]
Hi,

Yes, that unfortunately happens because conda is unfortunately not stable as maintainers keep deleting and changing prior versions of different packages. This creates dependencies issues every few weeks. I do not have the resources to update this right now but you can replace in the file `Snakefile` all instances of `envs/environment.yaml` by `envs/environment_minimal.yaml` and try to resolve/install with that one. (we replace that one at some point since it stopped resolving for some users but its entirely possible that it resolves now).
Hopefully this helps,
